// Define the type for the localConfig object
import { SiteConfig } from './configTypes';

// Export the LocalConfig interface as an alias for backward compatibility
export type LocalConfig = SiteConfig;

const localConfig: LocalConfig = {
  "showLogo": true,
  "infoBar": {
    "backgroundColor": "#1e40af",
    "phone": "(770) 495-0059",
    "address": "2785 Buford Hwy Ste 101-C, Duluth, GA 30096",
    "hours": "Mon-Fri: 8:30 AM - 6:00 PM",
    "textColor": "#ffffff",
    "message": "Expert Auto Body Repair & Collision Services"
  },
  "navBar": {
    "backgroundColor": "#ffffff",
    "textColor": "#1e40af",
    "logo": "TC-TITLE.png",
    "showLogo": false,
    "siteTitle": "Auto_Template",
    "siteTitleGradientFrom": "#1e40af",
    "siteTitleGradientTo": "#3b82f6",
    "scheduleButtonText": "Schedule Now",
    "scheduleButtonColor": "#1e40af",
    "activeTabColor": "#1e40af",
    "hamburgerIconColor": "#1e40af",
    "hamburgerIconHoverBgColor": "#1e40af20",
    "mobileMenuBgColor": "#ffffff",
    "mobileNavTextColor": "#111827",
    "mobileActiveTabBgColor": "#1e40af20",
    "mobileActiveTabTextColor": "#1e40af",
    "navLinks": [
      {
        "path": "/",
        "label": "Home"
      },
      {
        "path": "/services",
        "label": "Services"
      },
      {
        "path": "/reviews",
        "label": "Reviews"
      },
      {
        "path": "/contact",
        "label": "Contact"
      }
    ]
  },
  "cursor": {
    "enabled": true,
    "mobileEnabled": false,
    "cursorImage": "blkcursor.png",
    "elementCursorImage": "blucursor.png"
  },
  "loadingScreen": {
    "enabled": true,
    "backgroundColor": "rgba(59, 130, 245, 0.21)",
    "logoImage": "TC-TITLE.png",
    "logoWidth": 280,
    "logoAlt": "Taylor's Collision",
    "spinner": {
      "enabled": true,
      "color": "#1d4ed8",
      "size": 60,
      "thickness": 4
    },
    "timing": {
      "minimumDisplayTime": 300,
      "fadeOutDuration": 100
    }
  },
  "browser": {
    "title": "AutoTemplate - Premier Auto Body Shop in Savannah, GA",
    "shortTitle": "Auto Template",
    "faviconFolder": "favicon",
    "themeColor": "#1e40af"
  },
  "businessInfo": {
    "name": "Taylor's Collision",
    "llcType": "",
    "contactEmail": "support@taylorscollision.com",
    "contactPhone": "(770) 495-0050",
    "legalPages": {
      "privacyPolicy": {
        "headerColor": "#1e40af",
        "linkColor": "#3b82f6",
        "backgroundColor": "#ffffff",
        "textColor": "#1f1f1f",
        "borderColor": "#e5e7eb",
        "iconColor": "#1e40af"
      },
      "termsOfService": {
        "headerColor": "#1e40af",
        "linkColor": "#3b82f6",
        "backgroundColor": "#ffffff",
        "textColor": "#1f1f1f",
        "borderColor": "#e5e7eb",
        "disclaimerBgColor": "#f9fafb",
        "disclaimerTextColor": "#374151"
      }
    }
  },
  "pages": {
    "Home": {
      "badge": "Collision Auto Body Shop",
      "heroBadgeColor": "#3b82f620",
      "heroBadgeTitleColor": "#ffffff",
      "title": "Auto Body Repair in",
      "heroTitleColor": "#ffffff",
      "location": "Savannah, Ga",
      "heroLocationColor": "#85b4ff",
      "content": "",
      "heroContentColor": "#ffffff",
      "subtitle2": "Quality collision repair with exceptional customer service. Get your car back to pre-accident condition with our skilled technicians.",
      "heroSubtitleColor": "#e2f1ff",
      "heroImage": "auto1.png",
      "heroMobileImage": "TC-MOBILE-BG.png",
      "heroGradientTop": "rgba(30, 64, 176, 1)",
      "heroGradientBottom": "#1e3a8a",
      "scheduleButtonText": "Schedule Estimate",
      "heroScheduleButtonColor": "#1e40af",
      "heroScheduleButtonTextColor": "#ffffff",
      "heroScheduleButtonHoverColor": "#1d4ed8",
      "contactButtonText": "Contact Us",
      "heroContactButtonColor": "#00000000",
      "heroContactButtonTextColor": "#ffffff",
      "heroContactButtonBorderColor": "#ffffff",
      "heroContactButtonHoverColor": "rgba(24, 113, 255, 0.41)",
      "heroContactButtonHoverTextColor": "#1e40af",
      "heroContactButtonHoverBorderColor": "#ffffff",
      "heroCard1Text": "Free Estimates",
      "heroBox1BgColor": "#1e3a8a",
      "heroBox1TextColor": "#ffffff",
      "heroBox1BorderColor": "#3b82f6",
      "heroBox1IconBgColor": "#3b82f6",
      "heroBox1IconColor": "#ffffff",
      "heroCard2Text": "Expert Technicians",
      "heroBox2BgColor": "#1e3a8a",
      "heroBox2TextColor": "#ffffff",
      "heroBox2BorderColor": "#3b82f6",
      "heroBox2IconBgColor": "#3b82f6",
      "heroBox2IconColor": "#ffffff",
      "heroCard3Text": "Quick Turnaround",
      "heroBox3BgColor": "#1e3a8a",
      "heroBox3TextColor": "#ffffff",
      "heroBox3BorderColor": "#3b82f6",
      "heroBox3IconBgColor": "#3b82f6",
      "heroBox3IconColor": "#ffffff",
      "scheduleSection": {
        "scheduleSectionTitle": "BOOK YOUR SERVICE",
        "scheduleSectionTitleColor": "#1e40af",
        "scheduleSectionBadgeColor": "#3b82f636",
        "scheduleSectionBadgeTextColor": "#1e40af",
        "bookingTitle": "Schedule Your Auto Estimate",
        "bookingTitleColor": "#1e40af",
        "scheduleTitlePart1": "Book a time to bring your car to our ",
        "scheduleTitlePart1Color": "#111827",
        "scheduleTitlePart2": "expert technicians",
        "scheduleTitlePart2Color": "#1e40af",
        "scheduleIconBgColor": "#3b82f6",
        "scheduleIconColor": "#ffffff",
        "scheduleIconImage": "clock.png",
        "scheduleAddress": "2785 Buford Hwy Ste 101-C, Duluth, GA 30096",
        "scheduleAddressColor": "#1d4ed8",
        "scheduleContent": "We'll get your vehicle back to its best condition with professional collision repair services.",
        "scheduleContentColor": "#6b7280",
        "calendarRippleStartColor": "#93c5fd",
        "calendarRippleEndColor": "#60a5fa",
        "calendarRippleOpacity": 0.15,
        "calendarBgColor": "#ffffff",
        "calendarBorderColor": "#93c5fd",
        "calendarAccentColor": "#3b82f6",
        "calendarMonth": "AUGUST",
        "calendarYear": "2024",
        "calendarEmptyDays": "3",
        "calendarDaysInMonth": "31",
        "calendarSelectedDay": "15",
        "calendarAvailableDays": "5,8,12,15,19,22,26,29",
        "calendarTimeSlotsText": "3 Time Slots Available",
        "tapToBookText": "Tap to Book",
        "tapToBookTextColor": "#000000",
        "calendlyUrl": "https://calendly.com/[*ENTER_CALENDLY_URL*]",
        "scheduleGradientTop": "#dbeafe",
        "scheduleGradientBottom": "#ffffff"
      },
      "guaranteeSection": {
        "guaranteeTitle": "Our Guarantee",
        "guaranteeBadgeColor": "#dbeafec0",
        "guaranteeBadgeTextColor": "#1e40af",
        "guaranteeIcon1": "access.png",
        "guaranteeTitle1": "Lifetime Warranty",
        "guaranteeSubtitle1": "On All Services",
        "guaranteeIconBgColor1": "#ffffff",
        "guaranteeIconBorderColor1": "#dbeafe",
        "guaranteeTitleTextColor1": "#111827",
        "guaranteeSubtitleTextColor1": "#6b7280",
        "guaranteeIcon2": "free.png",
        "guaranteeTitle2": "Free Estimates",
        "guaranteeSubtitle2": "Quick & Accurate",
        "guaranteeIconBgColor2": "#ffffff",
        "guaranteeIconBorderColor2": "#dbeafe",
        "guaranteeTitleTextColor2": "#111827",
        "guaranteeSubtitleTextColor2": "#6b7280",
        "guaranteeCenterLogo": "ppg.png",
        "guaranteeCenterBgColor": "#ffffff",
        "guaranteeCenterBorderColor": "#dbeafe",
        "guaranteeIcon4": "calculator.png",
        "guaranteeTitle4": "Insurance Approved",
        "guaranteeSubtitle4": "All Major & Minor Companies",
        "guaranteeIconBgColor4": "#ffffff",
        "guaranteeIconBorderColor4": "#dbeafe",
        "guaranteeTitleTextColor4": "#111827",
        "guaranteeSubtitleTextColor4": "#6b7280",
        "guaranteeIcon5": "shipping.png",
        "guaranteeTitle5": "Towing Service",
        "guaranteeSubtitle5": "24/7 Available",
        "guaranteeIconBgColor5": "#ffffff",
        "guaranteeIconBorderColor5": "#dbeafe",
        "guaranteeTitleTextColor5": "#111827",
        "guaranteeSubtitleTextColor5": "#6b7280",
        "guaranteeIconBgColor": "#ffffff",
        "guaranteeIconBorderColor": "#e0e7ff",
        "guaranteeTitleTextColor": "#111827",
        "guaranteeSubtitleTextColor": "#6b7280",
        "guaranteeBgGradientTop": "f0f7fb",
        "guaranteeBgGradientBottom": "#f0f7fb",
        "guaranteeDecorativeElements": {
          "topCircleFromColor": "#c9f5c9ec",
          "topCircleToColor": "#99dac0",
          "topCircleOpacity": 0.3,
          "bottomCircleFromColor": "#c9f5c9ec",
          "bottomCircleToColor": "#99dac0",
          "bottomCircleOpacity": 0.3,
          "centerRadialColor": "#ffffff",
          "centerRadialOpacity": 0.8,
          "item1BgFromColor": "#c9f5c9",
          "item1BgViaColor": "#99dac0",
          "item1BgToColor": "#c9f5c9",
          "item2BgFromColor": "#c9f5c9",
          "item2BgViaColor": "#99dac0",
          "item2BgToColor": "#c9f5c9",
          "centerBgFromColor": "#c9f5c9",
          "centerBgViaColor": "#99dac0",
          "centerBgToColor": "#c9f5c9",
          "item4BgFromColor": "#c9f5c9",
          "item4BgViaColor": "#99dac0",
          "item4BgToColor": "#c9f5c9",
          "item5BgFromColor": "#c9f5c9",
          "item5BgViaColor": "#99dac0",
          "item5BgToColor": "#c9f5c9",
          "itemHoverFromColor": "#c9f5c9",
          "itemHoverToColor": "#99dac0"
        }
      },
      "servicesSection": {
        "servicesBadgeText": "Our Expertise",
        "servicesBadgeColor": "#dbeafe6b",
        "servicesBadgeTextColor": "#1e40af",
        "servicesTitle": "Expert Auto Body ",
        "servicesHighlightText": "Repair Services",
        "servicesTitleColor": "#111827",
        "servicesHighlightColor": "#1e40af",
        "servicesHighlightUnderlineColor": "#3b82f642",
        "servicesDescription": "We specialize in comprehensive auto body repair services, from collision repair and dent removal to expert paint matching and structural repairs.",
        "servicesDescriptionColor": "#6b7280",
        "servicesButtonText": "Explore Our Services",
        "servicesButtonUrl": "/services",
        "servicesButtonStartColor": "#1e40af",
        "servicesButtonEndColor": "#1e40af",
        "servicesButtonTextColor": "#ffffff",
        "servicesButtonHoverStartColor": "#1d4ed8",
        "servicesButtonHoverEndColor": "#1d4ed8",
        "serviceReelCardBgColor": "#ffffff",
        "serviceReelCardBorderColor": "#f3f4f680",
        "serviceReelCardHoverShadowColor": "rgba(0, 0, 0, 0.08)",
        "serviceReelIconColor": "#1e40af",
        "serviceReelTitleColor": "#111827",
        "serviceReelTitleHoverColor": "#1e40af",
        "serviceReelDescriptionColor": "#6b7280",
        "serviceReelDescriptionHoverColor": "#374151",
        "serviceReelMobileIndicatorColor": "#1e40af",
        "serviceReelMobileInactiveColor": "#e0e0e0",
        "serviceReelGradientFromColor": "#ffffff",
        "serviceReelGradientToColor": "#ffffff"
      },
      "reviewsSection": {
        "reviewsBadgeText": "Verified Google Reviews",
        "reviewsBadgeColor": "rgba(255, 255, 255, 0.1)",
        "reviewsBadgeTextColor": "#ffffff",
        "reviewsTitle": "Reviews from our",
        "reviewsHighlight": "community",
        "reviewsTitleColor": "#ffffff",
        "reviewsHighlightColor": "#93c5fd",
        "reviewsSubtitle": "We're committed to excellence",
        "reviewsSubtitleColor": "#e0f2fe",
        "reviewCardBgColor": "rgba(255, 255, 255, 0.1)",
        "reviewCardBorderColor": "rgba(255, 255, 255, 0.2)",
        "reviewCardHoverBorderColor": "rgba(255, 255, 255, 0.3)",
        "reviewTextColor": "rgba(255, 255, 255, 0.9)",
        "reviewAuthorColor": "#ffffff",
        "reviewVerifiedColor": "#ffffff",
        "reviewStarColor": "#fbbf24",
        "viewAllButtonText": "View All Reviews",
        "viewAllButtonBgColor": "rgba(255, 255, 255, 0.1)",
        "viewAllButtonHoverBgColor": "rgba(255, 255, 255, 0.2)",
        "viewAllButtonTextColor": "#ffffff",
        "viewAllButtonBorderColor": "rgba(255, 255, 255, 0.2)",
        "reviewsBgStartColor": "#3b82f6",
        "reviewsBgMiddleColor": "#2563eb",
        "reviewsBgEndColor": "#1e40af",
        "defaultReviews": [
          {
            "text": "Max and the team did an incredible job on my 2020 Mazda CX-30. I'm extremely happy with the results and would recommend them to everyone!",
            "author": "Jarrett B.",
            "rating": 5
          },
          {
            "text": "The owner Max was AMAZING!! His work is top notch! I think my vehicle actually looks better than it did before I had the accident!",
            "author": "Jordan P.",
            "rating": 5
          },
          {
            "text": "Had a door out of alignment and Max fixed it in just a few minutes. No appointment. Just rolled in off the street. Great place.",
            "author": "Rob G.",
            "rating": 5
          }
        ]
      }
    },
    "Services": {
      "title": "Our Auto Body Services",
      "heroTitleColor": "#ffffff",
      "subtitle": "Expert collision repair and auto body services in Duluth, GA. Quality work guaranteed.",
      "heroSubtitleColor": "#ffffff",
      "badge": "Certified Auto Body Shop",
      "heroBadgeBgColor": "#1e40af3a",
      "heroBadgeTextColor": "#ffffff",
      "heroBadgeIconColor": "#93c5fd",
      "heroBadgeCheckmarkColor": "#60a5fa",
      "heroBadgeMedalIconColor": "#3b82f6",
      "card1Title": "Years Experience",
      "card1Value": "15+",
      "card2Title": "Cars Repaired",
      "card2Value": "5000+",
      "heroStatsCardBgColor": "#1e40af4f",
      "heroStatsCardTextColor": "#ffffff",
      "heroStatsCardValueColor": "#ffffff",
      "heroStatsCardIconColor": "#93c5fd",
      "heroImage": "/images/auto-services-hero.jpg",
      "heroBgGradientFrom": "#1e40af",
      "heroBgGradientVia": "#1e3a8a",
      "heroBgGradientTo": "#1d4ed8",
      "heroBlurredCircle1Color": "#3b82f6",
      "heroBlurredCircle2Color": "#60a5fa",
      "heroPatternColor": "#ffffff",
      "heroLightBeam1Color": "#3b82f6",
      "heroLightBeam2Color": "#93c5fd",
      "serviceCategoriesBgColor": "#ffffff",
      "serviceCategoriesGradientOpacity": 0.7,
      "serviceCategoriesBgColorFrom": "#ffffff",
      "serviceCategoriesBgColorTo": "#ffffff",
      "serviceCategoryCardTitleColor": "#ffffff",
      "serviceCategoryCardDescriptionColor": "#0342c2",
      "serviceCategoryCardBorderColor": "#e5e7eb",
      "serviceCategoryCardButtonColor": "#ffffff",
      "serviceCategoryCardButtonBgColor": "rgba(255, 255, 255, 0.1)",
      "serviceCategoryCardButtonHoverBgColor": "#2ba99f",
      "serviceCategoryCardButtonHoverColor": "#ffffff",
      "serviceCategories": [
        {
          "id": "collision",
          "title": "Collision Services",
          "titleColor": "#ffffff",
          "description": "Complete collision repair services to restore your vehicle to pre-accident condition",
          "descriptionColor": "#ffffff",
          "bgImage": "auto2.png",
          "color": "#1e40af-#3b82f6",
          "iconColor": "#ffffff",
          "borderColor": "#1e40af",
          "icon": "WrenchScrewdriverIcon",
          "services": [
            {
              "title": "Collision Repair",
              "description": "Expert repair for all types of collision damage, restoring your vehicle to pre-accident condition with precision and care.",
              "icon": "WrenchScrewdriverIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Frame Straightening",
              "description": "Advanced frame repair and alignment services using state-of-the-art equipment to ensure structural integrity and safety.",
              "icon": "CogIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Paint & Refinishing",
              "description": "Professional automotive painting with computerized color matching to restore your vehicle's original appearance.",
              "icon": "PaintBrushIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Insurance Claims",
              "description": "Complete assistance with insurance claims processing, working directly with your insurance company for seamless repairs.",
              "icon": "WrenchIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            }
          ]
        },
        {
          "id": "cosmetic",
          "title": "Cosmetic Services",
          "titleColor": "#ffffff",
          "description": "Premium cosmetic services to enhance and protect your vehicle's appearance",
          "descriptionColor": "#ffffff",
          "bgImage": "auto3.png",
          "color": "#1e40af-#3b82f6",
          "iconColor": "#ffffff",
          "borderColor": "#1e40af",
          "icon": "SparklesIcon",
          "services": [
            {
              "title": "Auto Detailing",
              "description": "Comprehensive interior and exterior detailing services to restore your vehicle's showroom appearance and protect its value.",
              "icon": "SparklesIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Crown Thinning & Reduction",
              "description": "Selective removal of inner branches to reduce weight, improve light penetration, and lower wind resistance. This service is ideal for mature trees or those vulnerable to storm damage, preserving their strength and form.",
              "icon": "ShieldCheckIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Fruit Tree Pruning",
              "description": "Specialized pruning for fruit trees to increase yield, improve fruit quality, and maintain manageable sizes. We time our cuts to align with seasonal growth cycles, ensuring your orchard produces abundant, healthy fruit.",
              "icon": "WrenchScrewdriverIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Seasonal Tree Care",
              "description": "Ongoing maintenance to prepare trees for seasonal changes, including winter protection, spring growth encouragement, and fall cleanup. ",
              "icon": "CogIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            }
          ]
        },
        {
          "id": "mechanical",
          "title": "Mechanical Services",
          "titleColor": "#ffffff",
          "description": "Essential mechanical services and diagnostics for optimal vehicle performance",
          "bgImage": "auto4.png",
          "color": "#1e40af-#3b82f6",
          "iconColor": "#ffffff",
          "borderColor": "#1e40af",
          "descriptionColor": "#ffffff",
          "icon": "CogIcon",
          "services": [
            {
              "title": "Tree Removal & Cleanup",
              "description": "Our Tree Removal & Cleanup services tackle unwanted trees, stumps, and debris with precision and care. We ensure your property is left clean and ready for its next use, delivering efficient results without breaking the bank.",
              "icon": "BeakerIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Tree Removal",
              "description": "Safe removal of dead, diseased, or hazardous trees that threaten your property or safety. Using advanced rigging and cutting techniques, we dismantle trees in confined spaces, protecting your home and landscape.",
              "icon": "ExclamationTriangleIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Stump Grinding & Removal",
              "description": "Specialized fleet maintenance and repair",
              "icon": "TruckIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#000000",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Seasonal Tree Care",
              "description": "Ongoing maintenance tailored to seasonal needs, including leaf thinning, deadwood removal, and growth monitoring.",
              "icon": "WrenchIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            }
          ]
        }
      ],
      "ctaBgGradientFrom": "#1e40af",
      "ctaBgGradientVia": "#3b82f6",
      "ctaBgGradientTo": "#2563eb",
      "ctaBgPatternColor": "#ffffff60",
      "ctaCardBgColor": "#ffffff2f",
      "ctaCardBorderColor": "#ffffff20",
      "scheduleButtonText": "Schedule Now",
      "scheduleButtonBgColor": "#ffffff",
      "scheduleButtonTextColor": "#1e40af",
      "scheduleButtonHoverBgColor": "#f3f4f6",
      "callButtonText": "Call Us Now",
      "callButtonBgColor": "#1e40af",
      "callButtonTextColor": "#ffffff",
      "callButtonHoverBgColor": "#1d4ed8",
      "ctaTitle": "Ready to Get Your Car Back to Perfect?",
      "ctaTitleColor": "#ffffff",
      "ctaDescription": "Schedule your appointment today and experience the difference expert auto body repair makes.",
      "ctaDescriptionColor": "#ffffff"
    },
    "Reviews": {
      "title": "Customer Reviews",
      "heroTitleColor": "#ffffff",
      "subtitle": "We're proud of the work we do and the trust our customers place in us. Here's what they have to say about their collision repair experience.",
      "heroSubtitleColor": "#ffffff",
      "badge": "Verified Google Reviews",
      "heroBadgeBgColor": "#ffffff10",
      "heroBadgeTextColor": "#ffffff",
      "heroBadgeIconColor": "#93c5fd",
      "heroBadgeCheckmarkColor": "#3b82f6",
      "heroBadgeBorderColor": "#3b82f6",
      "statsCard1Title": "Verified Reviews",
      "statsCard1IconColor": "#93c5fd",
      "statsCard1BlurGradientFrom": "#1e40af",
      "statsCard1BlurGradientTo": "#3b82f6",
      "statsCard2Title": "Average Rating",
      "statsCard2IconColor": "#facc15",
      "statsCard2BlurGradientFrom": "#3b82f6",
      "statsCard2BlurGradientTo": "#1e40af",
      "statsCardBgColor": "#ffffff10",
      "statsCardTextColor": "#f3f4f6",
      "statsCardTitleColor": "#ffffff",
      "statsCardBorderColor": "#ffffff20",
      "statsCardHoverBorderColor": "#ffffff30",
      "heroImage": "/images/auto-reviews-hero.jpg",
      "heroBgGradientFrom": "#1e40af",
      "heroBgGradientVia": "#1e3a8a",
      "heroBgGradientTo": "#1d4ed8",
      "heroBlurredCircle1Color": "#3b82f6",
      "heroBlurredCircle2Color": "#60a5fa",
      "heroBlurredCircle3Color": "#93c5fd",
      "heroLightBeam1Color": "#3b82f6",
      "heroLightBeam2Color": "#60a5fa",
      "heroPatternColor": "#ffffff",
      "heroPatternOpacity": 0.1,
      "reviewsSectionBgColor": "#dbeafe2a",
      "reviewCardBgColor": "#ffffff",
      "reviewCardHoverShadow": "lg",
      "reviewCardBorderColor": "#e5e7eb",
      "reviewCardTextColor": "#4b5563",
      "reviewCardAuthorNameColor": "#111827",
      "reviewCardSourceColor": "#6b7280",
      "reviewCardStarColor": "#facc15",
      "reviewCardStarEmptyColor": "#d1d5db",
      "reviewCardShowMoreColor": "#1e40af",
      "reviewCardShowMoreHoverColor": "#3b82f6",
      "reviewCardGradientColor": "#1e40af",
      "reviewAvatarColors": [
        "#3b82f6",
        "#10b981",
        "#f59e0b",
        "#ef4444",
        "#8b5cf6",
        "#ec4899",
        "#6366f1",
        "#14b8a6"
      ],
      "reviewAvatarTextColor": "#ffffff",
      "paginationButtonBgColor": "#2563eb",
      "paginationButtonTextColor": "#ffffff",
      "paginationButtonDisabledOpacity": 0.5,
      "paginationTextColor": "#4b5563",
      "shareExperienceBgColor": "#ffffff",
      "shareExperienceBorderColor": "#e5e7eb",
      "shareExperienceShadow": "sm",
      "shareExperienceHoverShadow": "md",
      "shareExperienceTitleColor": "#111827",
      "shareExperienceSubtitleColor": "#4b5563",
      "shareExperienceGradientColor": "#1e40af",
      "shareExperienceGradientOpacity": 0.5,
      "shareButtonBgColor": "#1e40af",
      "shareButtonTextColor": "#ffffff",
      "shareButtonHoverBgColor": "#3b82f6",
      "shareButtonShadow": "sm",
      "shareButtonHoverShadow": "md",
      "shareButtonText": "Write a Review on Google",
      "shareButtonLink": "https://g.co/kgs/NVDcU7f",
      "shareExperienceTitle": "Share Your Experience",
      "shareExperienceSubtitle": "Help others by sharing your experience with us",
      "ctaBgGradientFrom": "#1e40af",
      "ctaBgGradientVia": "#3b82f6",
      "ctaBgGradientTo": "#2563eb",
      "ctaPatternColor": "#ffffff",
      "ctaPatternOpacity": 0.05,
      "ctaCardBgColor": "#ffffff0d",
      "ctaCardBlurAmount": "2px",
      "ctaScheduleButtonText": "Schedule Now",
      "ctaScheduleButtonBgColor": "#ffffff",
      "ctaScheduleButtonTextColor": "#2563eb",
      "ctaScheduleButtonHoverBgColor": "#f3f4f6",
      "ctaCallButtonText": "Call Us Now",
      "ctaCallButtonBgColor": "#2563eb",
      "ctaCallButtonTextColor": "#ffffff",
      "ctaCallButtonHoverBgColor": "#1d4ed8",
      "ctaTitle": "Ready to Get Your Car Back to Perfect?",
      "ctaTitleColor": "#ffffff",
      "ctaDescription": "Schedule your appointment today and experience the difference expert auto body repair makes.",
      "ctaDescriptionColor": "#93c5fd"
    },
    "Careers": {
      "heroPaddingTop": "150px",
      "heroBgGradientFrom": "#1e40af",
      "heroBgGradientVia": "#1e3a8a",
      "heroBgGradientTo": "#3b82f6",
      "heroBlurredCircle1Color": "#3b82f6",
      "heroBlurredCircle1Opacity": 0.2,
      "heroBlurredCircle2Color": "#60a5fa",
      "heroBlurredCircle2Opacity": 0.2,
      "heroPatternColor": "#ffffff",
      "heroPatternOpacity": 0.3,
      "waveSeparatorColor": "#1e40af81",
      "waveSeparatorHeight": "250px",
      "applicationSectionBgColor": "#ffffff",
      "applicationFormShadow": "0 25px 50px -12px rgba(0, 0, 0, 0.35)",
      "hireBadgeText": "We're hiring passionate professionals",
      "hireBadgeBgColor": "#ffffff10",
      "hireBadgeBorderColor": "#ffffff20",
      "hireBadgeTextColor": "#ffffff",
      "hireTitle": "Join Our Team",
      "hireTitleColor": "#ffffff",
      "hireTitleHighlightColor": "#ffffff",
      "hireTitleGlowColor": "#ffffff",
      "hireTitleGlowOpacity": 0.3,
      "hireSubtitle": "Build your career with Taylor's Collision. We're looking for talented individuals who are passionate about auto body repair and customer service.",
      "hireSubtitleColor": "#ffffff",
      "hireSubtitleOpacity": 0.9,
      "formHeaderBgFrom": "#3b82f6",
      "formHeaderBgTo": "#1e40af",
      "formHeaderPatternColor": "#ffffff",
      "formHeaderPatternOpacity": 0.15,
      "formHeaderPatternSize": "16px",
      "formHeaderTitleText": "Application Form",
      "formHeaderTitleColor": "#ffffff",
      "formHeaderSubtitleText": "Fill out the form below to apply for a position with our team",
      "formHeaderSubtitleColor": "#ffffff",
      "formHeaderSubtitleOpacity": 0.8,
      "formSectionBgColor": "#f9fafb",
      "formSectionBorderColor": "#e5e7eb",
      "formSectionTitleColor": "#1e40af",
      "formSectionHoverShadow": "md",
      "formInputBgColor": "#ffffff",
      "formInputBorderColor": "#d1d5db",
      "formInputTextColor": "#111827",
      "formInputFocusRingColor": "#3b82f6",
      "formInputFocusBorderColor": "#1e40af",
      "formInputBorderRadius": "xl",
      "formInputPadding": "px-4 py-3",
      "formLabelColor": "#374151",
      "formErrorColor": "#ef4444",
      "positionOptions": [
        "Auto Body Technician",
        "Collision Repair Specialist",
        "Paint Technician",
        "Frame Repair Technician",
        "Customer Service",
        "Other"
      ],
      "addReferenceBtnBgColor": "#1e40af",
      "addReferenceBtnHoverBgColor": "#1d4ed8",
      "addReferenceBtnTextColor": "#ffffff",
      "removeReferenceBtnColor": "#ef4444",
      "removeReferenceBtnHoverColor": "#dc2626",
      "submitButtonBgFrom": "#1e40af",
      "submitButtonBgTo": "#1d4ed8",
      "submitButtonTextColor": "#ffffff",
      "submitButtonHoverShadow": "xl",
      "submitButtonBorderRadius": "xl",
      "successMessageBgColor": "#dbeafe",
      "successMessageBorderColor": "#93c5fd",
      "successMessageTextColor": "#1e40af",
      "errorMessageBgColor": "#fef2f2",
      "errorMessageBorderColor": "#fecaca",
      "errorMessageTextColor": "#991b1b",
      "mobileOverlay": {
        "enabled": true,
        "mobileBreakpoint": 663,
        "title": "Desktop View Required",
        "message": "Our job application form requires a larger screen. Please visit this page on a desktop or laptop computer for the best experience.",
        "buttonText": "Back to Home Page",
        "buttonLink": "/",
        "footerText": "If you're already on a desktop device, please increase your browser window size.",
        "backgroundOpacity": 0.9,
        "overlayZIndex": 50,
        "cardBackgroundColor": "#ffffff",
        "cardBorderRadius": "2xl",
        "cardBorderTopWidth": 4,
        "cardBoxShadow": "2xl",
        "iconBackgroundOpacity": 0.3,
        "iconWidth": 20,
        "iconHeight": 20,
        "titleFontSize": "2xl",
        "titleFontWeight": "bold",
        "messageColor": "#4b5563",
        "buttonWidth": "full",
        "buttonPadding": "py-3 px-4",
        "buttonTextColor": "#ffffff",
        "buttonFontWeight": "medium",
        "buttonBorderRadius": "lg",
        "buttonShadow": "md",
        "buttonHoverScale": 1.05,
        "buttonTapScale": 0.95,
        "footerMarginTop": 6,
        "footerPaddingTop": 6,
        "footerBorderColor": "#e5e7eb",
        "footerTextColor": "#6b7280",
        "footerTextSize": "sm"
      }
    },
    "Contact": {
      "title": "Get in Touch",
      "heroTitleColor": "#ffffff",
      "heroTitleGradientFrom": "#ffffff",
      "heroTitleGradientVia": "#ffffff",
      "heroTitleGradientTo": "#ffffff",
      "heroTitleGlowColor": "#d2dceb",
      "heroTitleGlowOpacity": 0.3,
      "subtitle": "Have questions about collision repair? Need an estimate? We're here to help.",
      "heroSubtitleColor": "#ffffff",
      "heroSubtitleHighlightBgColor": "#1e40af",
      "badge": "Free Estimates Available",
      "heroBadgeBgColor": "#ffffff1a",
      "heroBadgeTextColor": "#ffffff",
      "heroBadgeIconColor": "#93c5fd",
      "heroBadgeBorderColor": "#ffffff33",
      "featureBadge1Text": "Expert Technicians",
      "featureBadge1IconColor": "#93c5fd",
      "featureBadge1BgColor": "#ffffff1a",
      "featureBadge1BorderColor": "#ffffff33",
      "featureBadge1TextColor": "#ffffff",
      "featureBadge2Text": "Insurance Assistance",
      "featureBadge2IconColor": "#93c5fd",
      "featureBadge2BgColor": "#ffffff1a",
      "featureBadge2BorderColor": "#ffffff33",
      "featureBadge2TextColor": "#ffffff",
      "heroImage": "/images/auto-contact-hero.jpg",
      "heroBgGradientFrom": "#1e40af",
      "heroBgGradientVia": "#3b82f6",
      "heroBgGradientTo": "#2563eb",
      "heroBlurredCircle1Color": "#3b82f6",
      "heroBlurredCircle1Opacity": 0.2,
      "heroBlurredCircle2Color": "#60a5fa",
      "heroBlurredCircle2Opacity": 0.2,
      "heroPatternColor": "#ffffff",
      "heroPatternOpacity": 0.3,
      "heroLightBeam1Color": "#3b82f6",
      "heroLightBeam1Opacity": 0.2,
      "heroLightBeam2Color": "#60a5fa",
      "heroLightBeam2Opacity": 0.2,
      "contactSectionBgColor": "#dbeafe1f",
      "contactInfoTitleText": "Contact Information",
      "contactInfoTitleColor": "#1e40af",
      "contactIconBgColor": "#dbeafe42",
      "contactIconColor": "#1e40af",
      "contactLabelColor": "#111827",
      "contactTextColor": "#4b5563",
      "contactLinkHoverColor": "#2563eb",
      "phoneIcon": "PhoneIcon",
      "phoneLabel": "Phone",
      "phoneNumber": "(770) 495-0050",
      "phoneNumberLink": "tel:+17704950050",
      "emailIcon": "EnvelopeIcon",
      "emailLabel": "Email",
      "emailAddress": "support@example.com",
      "emailAddressLink": "mailto:support@example.com",
      "locationIcon": "MapPinIcon",
      "locationLabel": "Location",
      "locationAddress": "2785 Buford Hwy Ste 101-C,\nDuluth, GA 30096",
      "hoursIcon": "ClockIcon",
      "hoursLabel": "Business Hours",
      "hoursText": "Monday - Friday: 8:30 AM - 6:00 PM\nSaturday - Sunday: Closed",
      "googleMapEmbedUrl": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3311.6728431479!2d-83.46847632413687!3d33.891119080637714!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88f6732844d0854f%3A0x58a2e0e5cc8ccae7!2sDavis%20Tree!5e0!3m2!1sen!2sus!4v1717270133598!5m2!1sen!2sus",
      "googleMapHeight": "300px",
      "googleMapBorderRadius": "lg",
      "googleMapShadow": "lg",
      "formTitleText": "Send Us a Message",
      "formTitleColor": "#111827",
      "formLabelColor": "#374151",
      "formInputBgColor": "#ffffff",
      "formInputBorderColor": "#d1d5db",
      "formInputTextColor": "#111827",
      "formInputFocusRingColor": "#3b82f6",
      "formInputBorderRadius": "lg",
      "formInputPadding": "px-4 py-3",
      "formFieldFullName": "Full Name",
      "formFieldEmail": "Email Address",
      "formFieldPhone": "Phone Number",
      "formFieldService": "Service Needed",
      "formFieldMessage": "Message",
      "serviceOptions": [
        "General Inquiry",
        "Collision Repair",
        "Auto Body Work",
        "Paint Services",
        "Insurance Claims",
        "Frame Repair",
        "Free Estimate"
      ],
      "formSubmitBtnText": "Send Message",
      "formSubmitBtnBgColor": "#1e40af",
      "formSubmitBtnTextColor": "#ffffff",
      "formSubmitBtnHoverBgColor": "#3b82f6",
      "formSubmitBtnBorderRadius": "lg",
      "ctaBgGradientFrom": "#1e40af",
      "ctaBgGradientVia": "#3b82f6",
      "ctaBgGradientTo": "#2563eb",
      "ctaPatternColor": "#ffffff",
      "ctaPatternOpacity": 0.05,
      "ctaCardBgColor": "#ffffff0d",
      "ctaCardBlurAmount": "2px",
      "ctaScheduleButtonText": "Schedule Now",
      "ctaScheduleButtonBgColor": "#ffffff",
      "ctaScheduleButtonTextColor": "#2563eb",
      "ctaScheduleButtonHoverBgColor": "#f3f4f6",
      "ctaCallButtonText": "Call Us Now",
      "ctaCallButtonBgColor": "#1e40af",
      "ctaCallButtonTextColor": "#ffffff",
      "ctaCallButtonHoverBgColor": "#3b82f6",
      "ctaTitle": "Ready to Get Your Car Back to Perfect?",
      "ctaTitleColor": "#ffffff",
      "ctaDescription": "Schedule your appointment today and experience the difference expert auto body repair makes.",
      "ctaDescriptionColor": "#e0f2fe"
    }
  },
  "theme": {
    "primary600": "#2563eb",
    "primary700": "#1d4ed8"
  },
  "navLinks": [
    {
      "path": "/",
      "label": "Home"
    },
    {
      "path": "/services",
      "label": "Services"
    },
    {
      "path": "/reviews",
      "label": "Reviews"
    },
    {
      "path": "/contact",
      "label": "Contact"
    }
  ],
  "policies": {
    "terms": "Our terms of service text here.",
    "privacy": "Our privacy policy text here."
  },
  "description": "Premier auto body shop in Savannah, GA - Expert collision repair",
  "contactInfo": {
    "address": "2785 Buford Hwy Ste 101-C, Duluth, GA 30096",
    "phone": "(770) 495-0050",
    "email": "support@taylorscollision.com"
  },
  "hours": {
    "weekday": "Monday - Friday: 8:30 AM - 6:00 PM",
    "weekend": "Saturday - Sunday: Closed"
  },
  "footerLinks": [
    {
      "path": "/",
      "label": "Home"
    },
    {
      "path": "/services",
      "label": "Services"
    },
    {
      "path": "/reviews",
      "label": "Reviews"
    },
    {
      "path": "/contact",
      "label": "Contact"
    }
  ],
  "socialLinks": {
    "twitter": "https://twitter.com/company",
    "facebook": "https://facebook.com/company",
    "linkedin": "https://linkedin.com/company/company",
    "instagram": "https://instagram.com/company"
  },
  "showJoinTeamButton": true,
  "joinTeamText": "Join the Team",
  "joinTeamLink": "/careers",
  "copyright": "© 2025 Taylor's Collision. All rights reserved.",
  "footerStyle": {
    "backgroundColor": "#ffffff",
    "gradientFromColor": "#dbeafe",
    "gradientToColor": "#ffffff",
    "titleColor": "#1e40af",
    "textColor": "#111827",
    "linkColor": "#1e40af",
    "linkHoverColor": "#3b82f6",
    "socialIconColor": "#1e40af",
    "dividerColor": "rgba(30, 64, 175, 0.2)",
    "quickLinksTitleColor": "#1e40af",
    "contactInfoTitleColor": "#1e40af",
    "infoTitleColor": "#1e40af",
    "joinButtonBgColor": "#1e40af",
    "joinButtonTextColor": "#ffffff",
    "joinButtonHoverBgColor": "#3b82f6",
    "hoursCardBgColor": "rgba(30, 64, 175, 0.04)",
    "hoursCardTextColor": "#111827",
    "hoursCardValueColor": "#1e40af",
    "copyrightTextColor": "#6b7280",
    "policyLinkColor": "#1e40af",
    "policyLinkHoverColor": "#3b82f6"
  },
  "schedulingButtonText": "Schedule Now",
  "themeColor": "#1e40af",
  "themeLink": "",
  "companyName": "Taylor's Collision"
};

export default localConfig;