// Define the type for the localConfig object
//supapass:RemovalTreeDavis321!
// Link For Hex Colors: https://www.color-hex.com/

import { SiteConfig } from "./configFixTypes";

// Export the LocalConfig interface as an alias for backward compatibility
export type LocalConfig = SiteConfig;

const localConfig: LocalConfig = {
  "showLogo": false,
  "infoBar": {
    "backgroundColor": "#0280c2",
    "phone": "(000) 000-0000",
    "address": "ADDRESS CURRENTLY UNAVAILABLE",
    "hours": "Monday - Friday: 9AM - 5PM",
    "textColor": "#000000",
    "message": "dsfddfs"
  },
  "navBar": {
    "backgroundColor": "#000000S",
    "textColor": "#000000",
    "logo": "dt-logo.png",
    "showLogo": true,
    "siteTitle": "Auto Site Template",
    "siteTitleGradientFrom": "#367658",
    "siteTitleGradientTo": "#0c2217",
    "scheduleButtonText": "Schedule Now",
    "scheduleButtonColor": "#1d4ed8",
    "activeTabColor": "#1d4ed8",
    "hamburgerIconColor": "#387e62",
    "hamburgerIconHoverBgColor": "#66bf9b20",
    "mobileMenuBgColor": "#ffffff",
    "mobileNavTextColor": "#111827",
    "mobileActiveTabBgColor": "#66bf9b20",
    "mobileActiveTabTextColor": "#387e62",
    "navLinks": [
      {
        "path": "/",
        "label": "Home"
      },
      {
        "path": "/services",
        "label": "Services"
      },
      {
        "path": "/reviews",
        "label": "Reviews"
      },
      {
        "path": "/contact",
        "label": "Contact"
      }
    ]
  },
  "cursor": {
    "enabled": true,
    "mobileEnabled": false,
    "cursorImage": "blkcursor.png",
    "elementCursorImage": "blucursor.png"
  },
  "loadingScreen": {
    "enabled": true,
    "backgroundColor": "#FFFFFF",
    "logoImage": "dt-logo.png",
    "logoWidth": 280,
    "logoAlt": "Davis Tree Service",
    "spinner": {
      "enabled": true,
      "color": "#66bf9b",
      "size": 60,
      "thickness": 4
    },
    "timing": {
      "minimumDisplayTime": 801,
      "fadeOutDuration": 500
    }
  },
  "browser": {
    "title": "Davis Tree Service - Professional Tree Care in Athens, GA",
    "shortTitle": "Davis Tree",
    "faviconFolder": "favicon",
    "themeColor": "#66bf9b"
  },
  "businessInfo": {
    "name": "Davis Tree Service",
    "llcType": "LLC",
    "contactEmail": "Jimmy@DavisTree.com",
    "contactPhone": "(706) 296-3318",
    "legalPages": {
      "privacyPolicy": {
        "headerColor": "#387e62",
        "linkColor": "#66bf9b",
        "backgroundColor": "#ffffff",
        "textColor": "#1f1f1f",
        "borderColor": "#e5e7eb",
        "iconColor": "#66bf9b"
      },
      "termsOfService": {
        "headerColor": "#387e62",
        "linkColor": "#66bf9b",
        "backgroundColor": "#ffffff",
        "textColor": "#1f1f1f",
        "borderColor": "#e5e7eb",
        "disclaimerBgColor": "#f9fafb",
        "disclaimerTextColor": "#374151"
      }
    }
  },
  "pages": {
    "Home": {
      "badge": "Auto Repair Shop",
      "heroBadgeColor": "#f5d6d61e",
      "heroBadgeTitleColor": "#000000",
      "title": "Welcome to  Site Template",
      "heroTitleColor": "#000000",
      "location": "",
      "heroLocationColor": "#363636",
      "content": "",
      "heroContentColor": "#ffffff",
      "subtitle2": "Quality collision repair with exceptional customer service. Get your car back to pre-accident condition with our skilled technicians.",
      "heroSubtitleColor": "#ffffff",
      "heroImage": "auto1.png",
      "heroGradientTop": "#005b96",
      "heroGradientBottom": "#03396c",
      "scheduleButtonText": "Schedule Now",
      "heroScheduleButtonColor": "#6497b1",
      "heroScheduleButtonTextColor": "#000000",
      "contactButtonText": "Contact Us",
      "heroContactButtonColor": "#ffffff",
      "heroContactButtonTextColor": "#ffffff",
      "heroContactButtonBorderColor": "#ffffff",
      "heroCard1Text": "*Free Estimates",
      "heroBox1BgColor": "#66bf9b1f",
      "heroBox1TextColor": "#ffffff",
      "heroBox1BorderColor": "#66bf9b",
      "heroBox1IconBgColor": "#7fd1b6",
      "heroBox1IconColor": "#000000",
      "heroCard2Text": "Licensed",
      "heroBox2BgColor": "#66bf9b1f",
      "heroBox2TextColor": "#ffffff",
      "heroBox2BorderColor": "#66bf9b",
      "heroBox2IconBgColor": "#7fd1b6",
      "heroBox2IconColor": "#000000",
      "heroCard3Text": "Fast Removal",
      "heroBox3BgColor": "#66bf9b1f",
      "heroBox3TextColor": "#ffffff",
      "heroBox3BorderColor": "#66bf9b",
      "heroBox3IconBgColor": "#7fd1b6",
      "heroBox3IconColor": "#000000",
      "scheduleSection": {
        "scheduleSectionTitle": "REQUEST A FREE ESTIMATE BELOW",
        "scheduleSectionTitleColor": "#53a584",
        "scheduleSectionBadgeColor": "#f5d6d636",
        "scheduleSectionBadgeTextColor": "#387e62",
        "bookingTitle": "BOOK YOUR SERVICE",
        "bookingTitleColor": "#387e62",
        "scheduleTitlePart1": "Get Your ",
        "scheduleTitlePart1Color": "#3d725d",
        "scheduleTitlePart2": "Free Quote Now",
        "scheduleTitlePart2Color": "#3d725d",
        "scheduleIconBgColor": "#5bab8b",
        "scheduleIconColor": "#ffffff",
        "scheduleIconImage": "clock.png",
        "scheduleAddress": "*ENTER_ADDRESS_HERE*",
        "scheduleAddressColor": "#ffffff00",
        "scheduleContent": "Ready to tackle that tree problem? We'll visit your property to assess the job and provide a transparent quote.",
        "scheduleContentColor": "#6b7280",
        "calendarRippleStartColor": "#9ddac0",
        "calendarRippleEndColor": "#a3d8c3",
        "calendarRippleOpacity": 0.15,
        "calendarBgColor": "#ffffff",
        "calendarBorderColor": "#99dac0",
        "calendarAccentColor": "#7dae99",
        "calendarMonth": "AUGUST",
        "calendarYear": "2024",
        "calendarEmptyDays": "3",
        "calendarDaysInMonth": "31",
        "calendarSelectedDay": "15",
        "calendarAvailableDays": "5,8,12,15,19,22,26,29",
        "calendarTimeSlotsText": "3 Time Slots Available",
        "tapToBookText": "Tap to Book",
        "tapToBookTextColor": "#000000",
        "calendlyUrl": "https://calendly.com/[*ENTER_CALENDLY_URL*]",
        "scheduleGradientTop": "#ceffec",
        "scheduleGradientBottom": "#ffffff"
      },
      "guaranteeSection": {
        "guaranteeTitle": "Our Guarantee",
        "guaranteeBadgeColor": "#c9f5c9ec",
        "guaranteeBadgeTextColor": "#000000",
        "guaranteeIcon1": "clock.png",
        "guaranteeTitle1": "Lifetime Warranty",
        "guaranteeSubtitle1": "On All Services",
        "guaranteeIconBgColor1": "#ffffff",
        "guaranteeIconBorderColor1": "#e0e7ff",
        "guaranteeTitleTextColor1": "#111827",
        "guaranteeSubtitleTextColor1": "#6b7280",
        "guaranteeIcon2": "clock.png",
        "guaranteeTitle2": "Free Estimates",
        "guaranteeSubtitle2": "Quick & Accurate",
        "guaranteeIconBgColor2": "#ffffff",
        "guaranteeIconBorderColor2": "#e0e7ff",
        "guaranteeTitleTextColor2": "#111827",
        "guaranteeSubtitleTextColor2": "#6b7280",
        "guaranteeCenterLogo": "clock.png",
        "guaranteeCenterBgColor": "#ffffff",
        "guaranteeCenterBorderColor": "#e0e7ff",
        "guaranteeIcon4": "clock.png",
        "guaranteeTitle4": "Insurance Approved",
        "guaranteeSubtitle4": "All Major & Minor Companies",
        "guaranteeIconBgColor4": "#ffffff",
        "guaranteeIconBorderColor4": "#e0e7ff",
        "guaranteeTitleTextColor4": "#111827",
        "guaranteeSubtitleTextColor4": "#6b7280",
        "guaranteeIcon5": "clock.png",
        "guaranteeTitle5": "Towing Service",
        "guaranteeSubtitle5": "24/7 Available",
        "guaranteeIconBgColor5": "#ffffff",
        "guaranteeIconBorderColor5": "#e0e7ff",
        "guaranteeTitleTextColor5": "#111827",
        "guaranteeSubtitleTextColor5": "#6b7280",
        "guaranteeIconBgColor": "#ffffff",
        "guaranteeIconBorderColor": "#e0e7ff",
        "guaranteeTitleTextColor": "#111827",
        "guaranteeSubtitleTextColor": "#6b7280",
        "guaranteeBgGradientTop": "#ffffff",
        "guaranteeBgGradientBottom": "#f0f9ff",
        "guaranteeDecorativeElements": {
          "topCircleFromColor": "#c9f5c9ec",
          "topCircleToColor": "#99dac0",
          "topCircleOpacity": 0.3,
          "bottomCircleFromColor": "#c9f5c9ec",
          "bottomCircleToColor": "#99dac0",
          "bottomCircleOpacity": 0.3,
          "centerRadialColor": "#ffffff",
          "centerRadialOpacity": 0.8,
          "item1BgFromColor": "#c9f5c9",
          "item1BgViaColor": "#99dac0",
          "item1BgToColor": "#c9f5c9",
          "item2BgFromColor": "#c9f5c9",
          "item2BgViaColor": "#99dac0",
          "item2BgToColor": "#c9f5c9",
          "centerBgFromColor": "#c9f5c9",
          "centerBgViaColor": "#99dac0",
          "centerBgToColor": "#c9f5c9",
          "item4BgFromColor": "#c9f5c9",
          "item4BgViaColor": "#99dac0",
          "item4BgToColor": "#c9f5c9",
          "item5BgFromColor": "#c9f5c9",
          "item5BgViaColor": "#99dac0",
          "item5BgToColor": "#c9f5c9",
          "itemHoverFromColor": "#c9f5c9",
          "itemHoverToColor": "#99dac0"
        }
      },
      "servicesSection": {
        "servicesBadgeText": "Our Expertise",
        "servicesBadgeColor": "#c1f3c56b",
        "servicesBadgeTextColor": "#387e62",
        "servicesTitle": "Comprehensive Tree ",
        "servicesHighlightText": "Care Services",
        "servicesTitleColor": "#111827",
        "servicesHighlightColor": "#246043",
        "servicesHighlightUnderlineColor": "#66bf9b42",
        "servicesDescription": "Davis Tree offers a full range of services to keep your trees healthy and your property safe. Our prices are transparent, and our work is unmatched.",
        "servicesDescriptionColor": "#6b7280",
        "servicesButtonText": "Explore Our Services",
        "servicesButtonUrl": "/services",
        "servicesButtonStartColor": "#387e62",
        "servicesButtonEndColor": "#387e62",
        "servicesButtonTextColor": "#ffffff",
        "serviceReelCardBgColor": "#ffffff",
        "serviceReelCardBorderColor": "#f3f4f680",
        "serviceReelCardHoverShadowColor": "rgba(0, 0, 0, 0.08)",
        "serviceReelIconColor": "#387e62",
        "serviceReelTitleColor": "#111827",
        "serviceReelTitleHoverColor": "#387e62",
        "serviceReelDescriptionColor": "#6b7280",
        "serviceReelDescriptionHoverColor": "#374151",
        "serviceReelMobileIndicatorColor": "#387e62",
        "serviceReelMobileInactiveColor": "#e0e0e0",
        "serviceReelGradientFromColor": "#ffffff",
        "serviceReelGradientToColor": "#ffffff"
      },
      "reviewsSection": {
        "reviewsBadgeText": "Verified Google Reviews",
        "reviewsBadgeColor": "rgba(255, 255, 255, 0.1)",
        "reviewsBadgeTextColor": "#ffffff",
        "reviewsTitle": "What Our Customers",
        "reviewsHighlight": "Are Saying",
        "reviewsTitleColor": "#ffffff",
        "reviewsHighlightColor": "#387e62",
        "reviewsSubtitle": "See what our satisfied customers have to say about our service.",
        "reviewsSubtitleColor": "#e0f2fe",
        "reviewCardBgColor": "rgba(255, 255, 255, 0.1)",
        "reviewCardBorderColor": "rgba(255, 255, 255, 0.2)",
        "reviewCardHoverBorderColor": "rgba(255, 255, 255, 0.3)",
        "reviewTextColor": "rgba(255, 255, 255, 0.9)",
        "reviewAuthorColor": "#ffffff",
        "reviewVerifiedColor": "#ffffff",
        "reviewStarColor": "#fbbf24",
        "viewAllButtonText": "View All Reviews",
        "viewAllButtonBgColor": "rgba(255, 255, 255, 0.1)",
        "viewAllButtonHoverBgColor": "rgba(255, 255, 255, 0.2)",
        "viewAllButtonTextColor": "#ffffff",
        "viewAllButtonBorderColor": "rgba(255, 255, 255, 0.2)",
        "reviewsBgStartColor": "#7dd0ae",
        "reviewsBgMiddleColor": "#66bf9b",
        "reviewsBgEndColor": "#53a584",
        "defaultReviews": [
          {
            "text": "Absolutely phenomenal work! My car looks even better than before the accident. The attention to detail and craftsmanship is top-notch. I highly recommend their services.",
            "author": "Jennifer R.",
            "rating": 5
          },
          {
            "text": "Fast, professional service from start to finish. They handled my insurance claim seamlessly and kept me updated throughout the entire repair process. Couldn't be happier with the results!",
            "author": "Michael S.",
            "rating": 5
          },
          {
            "text": "The team truly went above and beyond my expectations. Not only was my car repaired perfectly, but they also detailed it before returning it to me. Excellent customer service and quality work.",
            "author": "David W.",
            "rating": 5
          }
        ]
      }
    },
    "Services": {
      "title": "Our Services",
      "heroTitleColor": "#ffffff",
      "subtitle": "Explore our services below and let us help you cultivate a healthier, greener landscape.",
      "heroSubtitleColor": "#ffffff",
      "badge": "Certified Arborists",
      "heroBadgeBgColor": "#06ac143a",
      "heroBadgeTextColor": "#ffffff",
      "heroBadgeIconColor": "#60a5fa",
      "heroBadgeCheckmarkColor": "#4ade80",
      "heroBadgeMedalIconColor": "#66bf9b",
      "card1Title": "Years Experience",
      "card1Value": "20",
      "card2Title": "Trees Removed",
      "card2Value": "400+",
      "heroStatsCardBgColor": "#10500a4f",
      "heroStatsCardTextColor": "#ffffff",
      "heroStatsCardValueColor": "#ffffff",
      "heroStatsCardIconColor": "#60fa7a",
      "heroImage": "/images/service-hero.jpg",
      "heroBgGradientFrom": "#367658",
      "heroBgGradientVia": "#11492d",
      "heroBgGradientTo": "#0c2217",
      "heroBlurredCircle1Color": "#7dd0ae",
      "heroBlurredCircle2Color": "#53a584",
      "heroPatternColor": "#ffffff",
      "heroLightBeam1Color": "#53a584",
      "heroLightBeam2Color": "#7dd0ae",
      "serviceCategoriesBgColor": "#ffffff",
      "serviceCategoriesGradientOpacity": 0.7,
      "serviceCategoriesBgColorFrom": "#ffffff",
      "serviceCategoriesBgColorTo": "#ffffff",
      "serviceCategoryCardTitleColor": "#ffffff",
      "serviceCategoryCardDescriptionColor": "#0342c2",
      "serviceCategoryCardBorderColor": "#e5e7eb",
      "serviceCategoryCardButtonColor": "#ffffff",
      "serviceCategoryCardButtonBgColor": "rgba(255, 255, 255, 0.1)",
      "serviceCategoryCardButtonHoverBgColor": "#2ba99f",
      "serviceCategoryCardButtonHoverColor": "#ffffff",
      "serviceCategories": [
        {
          "id": "collision",
          "title": "Emergency and Health Services",
          "titleColor": "#ffffff",
          "description": "From storm damage to disease prevention, we're here to protect your trees and property 24/7.",
          "descriptionColor": "#ffffff",
          "bgImage": "davis2.png",
          "color": "#53a584-#53a584",
          "iconColor": "#000000",
          "borderColor": "#53a584",
          "icon": "ExclamationTriangleIcon",
          "services": [
            {
              "title": "Emergency Tree Services",
              "description": "Immediate response to storm-damaged or fallen trees, including hazardous limbs threatening structures.",
              "icon": "WrenchScrewdriverIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Tree Health Assessments & Treatment",
              "description": "Certified arborists diagnose pests, diseases, or nutrient issues and provide tailored treatments like insect control, fertilization, or soil care to restore tree health.",
              "icon": "CogIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Cabling & Bracing",
              "description": "We install discreet cables and braces to stabilize weak or overextended trees, preventing collapse and extending their lifespan without removal.",
              "icon": "PaintBrushIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Tree Risk Assessments",
              "description": "Proactive inspections to identify potential hazards, such as weak branches or unstable roots, before they become costly problems.",
              "icon": "WrenchIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            }
          ]
        },
        {
          "id": "cosmetic",
          "title": "Tree Maintenance",
          "titleColor": "#ffffff",
          "description": "Our Tree Maintenance services focus on enhancing the health, safety, and aesthetics of your trees.",
          "descriptionColor": "#ffffff",
          "bgImage": "davis3.png",
          "color": "#53a584-#53a584",
          "iconColor": "#000000",
          "borderColor": "#53a584",
          "icon": "SparklesIcon",
          "services": [
            {
              "title": "Tree Trimming & Pruning",
              "description": "Expert trimming and pruning to shape trees, remove dead or overgrown branches, and promote healthy growth. We tailor our cuts to improve air circulation, sunlight exposure, and structural integrity, enhancing both beauty and safety.",
              "icon": "SparklesIcon",
              "iconColor": "#3bf63b",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Crown Thinning & Reduction",
              "description": "Selective removal of inner branches to reduce weight, improve light penetration, and lower wind resistance. This service is ideal for mature trees or those vulnerable to storm damage, preserving their strength and form.",
              "icon": "ShieldCheckIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Fruit Tree Pruning",
              "description": "Specialized pruning for fruit trees to increase yield, improve fruit quality, and maintain manageable sizes. We time our cuts to align with seasonal growth cycles, ensuring your orchard produces abundant, healthy fruit.",
              "icon": "WrenchScrewdriverIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Seasonal Tree Care",
              "description": "Ongoing maintenance to prepare trees for seasonal changes, including winter protection, spring growth encouragement, and fall cleanup. ",
              "icon": "CogIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            }
          ]
        },
        {
          "id": "Tree Removal & Cleanup",
          "title": "Tree Removal & Cleanup",
          "titleColor": "#ffffff",
          "description": "Our Tree Removal & Cleanup services provide fast, thorough solutions for removing hazardous trees, stumps, or debris.",
          "bgImage": "davis4.png",
          "color": "#53a584-#53a584",
          "iconColor": "#000000",
          "borderColor": "#53a584",
          "descriptionColor": "#f3f4f6",
          "icon": "CogIcon",
          "services": [
            {
              "title": "Tree Removal & Cleanup",
              "description": "Our Tree Removal & Cleanup services tackle unwanted trees, stumps, and debris with precision and care. We ensure your property is left clean and ready for its next use, delivering efficient results without breaking the bank.",
              "icon": "BeakerIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Tree Removal",
              "description": "Safe removal of dead, diseased, or hazardous trees that threaten your property or safety. Using advanced rigging and cutting techniques, we dismantle trees in confined spaces, protecting your home and landscape.",
              "icon": "ExclamationTriangleIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Stump Grinding & Removal",
              "description": "Specialized fleet maintenance and repair",
              "icon": "TruckIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#000000",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            },
            {
              "title": "Seasonal Tree Care",
              "description": "Ongoing maintenance tailored to seasonal needs, including leaf thinning, deadwood removal, and growth monitoring.",
              "icon": "WrenchIcon",
              "iconColor": "#3b82f6",
              "titleColor": "#111827",
              "descriptionColor": "#6b7280",
              "bgColor": "#f9fafb",
              "borderColor": "#e5e7eb"
            }
          ]
        }
      ],
      "ctaBgGradientFrom": "#7dd0ae",
      "ctaBgGradientVia": "#53a584",
      "ctaBgGradientTo": "#387e62",
      "ctaBgPatternColor": "#ffffff60",
      "ctaCardBgColor": "#ffffff2f",
      "ctaCardBorderColor": "#961111S",
      "scheduleButtonText": "Schedule Now",
      "scheduleButtonBgColor": "#7dd0ae",
      "scheduleButtonTextColor": "#000000",
      "scheduleButtonHoverBgColor": "#ffffff",
      "callButtonText": "Call Us Now",
      "callButtonBgColor": "#ffffff",
      "callButtonTextColor": "#387e62",
      "callButtonHoverBgColor": "#7dd0ae",
      "ctaTitle": "Ready to free estimate?",
      "ctaTitleColor": "#ffffff",
      "ctaDescription": "Schedule your  today and experience the difference expert tree care makes.",
      "ctaDescriptionColor": "#ffffff"
    },
    "Reviews": {
      "title": "Community Reviews",
      "heroTitleColor": "#ffffff",
      "subtitle": "We're proud of the work we do and the trust our customers place in us. Here's what they have to say about their experience with our services.",
      "heroSubtitleColor": "#ffffff",
      "badge": "Verified Google Reviews",
      "heroBadgeBgColor": "#ffffff10",
      "heroBadgeTextColor": "#ffffff",
      "heroBadgeIconColor": "#60a5fa",
      "heroBadgeCheckmarkColor": "#7dd0ae",
      "heroBadgeBorderColor": "#7dd0ae",
      "statsCard1Title": "Verified Reviews",
      "statsCard1IconColor": "#60a5fa",
      "statsCard1BlurGradientFrom": "#4f46e5",
      "statsCard1BlurGradientTo": "#60a5fa",
      "statsCard2Title": "Average Rating",
      "statsCard2IconColor": "#facc15",
      "statsCard2BlurGradientFrom": "#60a5fa",
      "statsCard2BlurGradientTo": "#4f46e5",
      "statsCardBgColor": "#ffffff10",
      "statsCardTextColor": "#f3f4f6",
      "statsCardTitleColor": "#ffffff",
      "statsCardBorderColor": "#ffffff20",
      "statsCardHoverBorderColor": "#ffffff30",
      "heroImage": "/images/reviews-hero.jpg",
      "heroBgGradientFrom": "#367658",
      "heroBgGradientVia": "#11492d",
      "heroBgGradientTo": "#0c2217",
      "heroBlurredCircle1Color": "#3b82f6",
      "heroBlurredCircle2Color": "#60a5fa",
      "heroBlurredCircle3Color": "#93c5fd",
      "heroLightBeam1Color": "#60a5fa",
      "heroLightBeam2Color": "#93c5fd",
      "heroPatternColor": "#ffffff",
      "heroPatternOpacity": 0.1,
      "reviewsSectionBgColor": "#7dd0ad2a",
      "reviewCardBgColor": "#ffffff",
      "reviewCardHoverShadow": "lg",
      "reviewCardBorderColor": "#e5e7eb",
      "reviewCardTextColor": "#4b5563",
      "reviewCardAuthorNameColor": "#111827",
      "reviewCardSourceColor": "#6b7280",
      "reviewCardStarColor": "#facc15",
      "reviewCardStarEmptyColor": "#d1d5db",
      "reviewCardShowMoreColor": "#0f3622",
      "reviewCardShowMoreHoverColor": "#367658",
      "reviewCardGradientColor": "#0ea5e9",
      "reviewAvatarColors": [
        "#3b82f6",
        "#10b981",
        "#f59e0b",
        "#ef4444",
        "#8b5cf6",
        "#ec4899",
        "#6366f1",
        "#14b8a6"
      ],
      "reviewAvatarTextColor": "#ffffff",
      "paginationButtonBgColor": "#2563eb",
      "paginationButtonTextColor": "#ffffff",
      "paginationButtonDisabledOpacity": 0.5,
      "paginationTextColor": "#4b5563",
      "shareExperienceBgColor": "#ffffff",
      "shareExperienceBorderColor": "#e5e7eb",
      "shareExperienceShadow": "sm",
      "shareExperienceHoverShadow": "md",
      "shareExperienceTitleColor": "#111827",
      "shareExperienceSubtitleColor": "#4b5563",
      "shareExperienceGradientColor": "#288d4a",
      "shareExperienceGradientOpacity": 0.5,
      "shareButtonBgColor": "#0f3622",
      "shareButtonTextColor": "#ffffff",
      "shareButtonHoverBgColor": "#367658",
      "shareButtonShadow": "sm",
      "shareButtonHoverShadow": "md",
      "shareButtonText": "Write a Review on Google",
      "shareButtonLink": "https://g.co/kgs/NVDcU7f",
      "shareExperienceTitle": "Share Your Experience",
      "shareExperienceSubtitle": "Help others by sharing your experience with us",
      "ctaBgGradientFrom": "#1e40af",
      "ctaBgGradientVia": "#3b82f6",
      "ctaBgGradientTo": "#2563eb",
      "ctaPatternColor": "#ffffff",
      "ctaPatternOpacity": 0.05,
      "ctaCardBgColor": "#ffffff0d",
      "ctaCardBlurAmount": "2px",
      "ctaScheduleButtonText": "Schedule Now",
      "ctaScheduleButtonBgColor": "#ffffff",
      "ctaScheduleButtonTextColor": "#2563eb",
      "ctaScheduleButtonHoverBgColor": "#f3f4f6",
      "ctaCallButtonText": "Call Us Now",
      "ctaCallButtonBgColor": "#2563eb",
      "ctaCallButtonTextColor": "#ffffff",
      "ctaCallButtonHoverBgColor": "#1d4ed8",
      "ctaTitle": "Ready to Get Your Car Back to Perfect?",
      "ctaTitleColor": "#ffffff",
      "ctaDescription": "Schedule your appointment today and experience the difference expert auto body repair makes.",
      "ctaDescriptionColor": "#93c5fd"
    },
    "Careers": {
      "heroPaddingTop": "150px",
      "heroBgGradientFrom": "#387e62",
      "heroBgGradientVia": "#0c2217",
      "heroBgGradientTo": "#246043",
      "heroBlurredCircle1Color": "#098633",
      "heroBlurredCircle1Opacity": 0.2,
      "heroBlurredCircle2Color": "#1caa3a",
      "heroBlurredCircle2Opacity": 0.2,
      "heroPatternColor": "#ffffff",
      "heroPatternOpacity": 0.3,
      "waveSeparatorColor": "#0c221781",
      "waveSeparatorHeight": "250px",
      "applicationSectionBgColor": "#ffffff",
      "applicationFormShadow": "0 25px 50px -12px rgba(0, 0, 0, 0.35)",
      "hireBadgeText": "We're hiring passionate professionals",
      "hireBadgeBgColor": "#ffffff10",
      "hireBadgeBorderColor": "#ffffff20",
      "hireBadgeTextColor": "#ffffff",
      "hireTitle": "Join Our Team",
      "hireTitleColor": "#ffffff",
      "hireTitleHighlightColor": "#ffffff",
      "hireTitleGlowColor": "#ffffff",
      "hireTitleGlowOpacity": 0.3,
      "hireSubtitle": "Build your career with Davis Tree Service. We're looking for talented individuals who are passionate about tree care and customer service.",
      "hireSubtitleColor": "#ffffff",
      "hireSubtitleOpacity": 0.9,
      "formHeaderBgFrom": "#66bf9b",
      "formHeaderBgTo": "#387e62",
      "formHeaderPatternColor": "#ffffff",
      "formHeaderPatternOpacity": 0.15,
      "formHeaderPatternSize": "16px",
      "formHeaderTitleText": "Application Form",
      "formHeaderTitleColor": "#ffffff",
      "formHeaderSubtitleText": "Fill out the form below to apply for a position with our team",
      "formHeaderSubtitleColor": "#ffffff",
      "formHeaderSubtitleOpacity": 0.8,
      "formSectionBgColor": "#f9fafb",
      "formSectionBorderColor": "#e5e7eb",
      "formSectionTitleColor": "#126e40",
      "formSectionHoverShadow": "md",
      "formInputBgColor": "#ffffff",
      "formInputBorderColor": "#d1d5db",
      "formInputTextColor": "#111827",
      "formInputFocusRingColor": "#4bf63b",
      "formInputFocusBorderColor": "#126e40",
      "formInputBorderRadius": "xl",
      "formInputPadding": "px-4 py-3",
      "formLabelColor": "#374151",
      "formErrorColor": "#ef4444",
      "positionOptions": [
        "Tree Removal Specialist",
        "Arborist",
        "Groundskeeper",
        "Stump Grinder",
        "Customer Service",
        "Other"
      ],
      "addReferenceBtnBgColor": "#126e40",
      "addReferenceBtnHoverBgColor": "#0d5730",
      "addReferenceBtnTextColor": "#ffffff",
      "removeReferenceBtnColor": "#ef4444",
      "removeReferenceBtnHoverColor": "#dc2626",
      "submitButtonBgFrom": "#126e40",
      "submitButtonBgTo": "#0c2217",
      "submitButtonTextColor": "#ffffff",
      "submitButtonHoverShadow": "xl",
      "submitButtonBorderRadius": "xl",
      "successMessageBgColor": "#f0fdf4",
      "successMessageBorderColor": "#86efac",
      "successMessageTextColor": "#166534",
      "errorMessageBgColor": "#fef2f2",
      "errorMessageBorderColor": "#fecaca",
      "errorMessageTextColor": "#991b1b",
      "mobileOverlay": {
        "enabled": true,
        "mobileBreakpoint": 663,
        "title": "Desktop View Required",
        "message": "Our job application form requires a larger screen. Please visit this page on a desktop or laptop computer for the best experience.",
        "buttonText": "Back to Home Page",
        "buttonLink": "/",
        "footerText": "If you're already on a desktop device, please increase your browser window size.",
        "backgroundOpacity": 0.9,
        "overlayZIndex": 50,
        "cardBackgroundColor": "#ffffff",
        "cardBorderRadius": "2xl",
        "cardBorderTopWidth": 4,
        "cardBoxShadow": "2xl",
        "iconBackgroundOpacity": 0.3,
        "iconWidth": 20,
        "iconHeight": 20,
        "titleFontSize": "2xl",
        "titleFontWeight": "bold",
        "messageColor": "#4b5563",
        "buttonWidth": "full",
        "buttonPadding": "py-3 px-4",
        "buttonTextColor": "#ffffff",
        "buttonFontWeight": "medium",
        "buttonBorderRadius": "lg",
        "buttonShadow": "md",
        "buttonHoverScale": 1.05,
        "buttonTapScale": 0.95,
        "footerMarginTop": 6,
        "footerPaddingTop": 6,
        "footerBorderColor": "#e5e7eb",
        "footerTextColor": "#6b7280",
        "footerTextSize": "sm"
      }
    },
    "Contact": {
      "title": "Get in Touch",
      "heroTitleColor": "#ffffff",
      "heroTitleGradientFrom": "#ffffff",
      "heroTitleGradientVia": "#ffffff",
      "heroTitleGradientTo": "#ffffff",
      "heroTitleGlowColor": "#d2dceb",
      "heroTitleGlowOpacity": 0.3,
      "subtitle": "Have questions about our services? Need an estimate? We're here to help.",
      "heroSubtitleColor": "#ffffffff",
      "heroSubtitleHighlightBgColor": "#387e62",
      "badge": "24/7 Customer Support",
      "heroBadgeBgColor": "#ffffff1a",
      "heroBadgeTextColor": "#ffffff",
      "heroBadgeIconColor": "#7dd0ae",
      "heroBadgeBorderColor": "#ffffff33",
      "featureBadge1Text": "24/7 AI Assistant",
      "featureBadge1IconColor": "#7dd0ae",
      "featureBadge1BgColor": "#ffffff1a",
      "featureBadge1BorderColor": "#ffffff33",
      "featureBadge1TextColor": "#ffffff",
      "featureBadge2Text": "Expert Consultation",
      "featureBadge2IconColor": "#7dd0ae",
      "featureBadge2BgColor": "#ffffff1a",
      "featureBadge2BorderColor": "#ffffff33",
      "featureBadge2TextColor": "#ffffff",
      "heroImage": "/images/contact-hero.jpg",
      "heroBgGradientFrom": "#7dd0ae",
      "heroBgGradientVia": "#387e62",
      "heroBgGradientTo": "#367658",
      "heroBlurredCircle1Color": "#098633",
      "heroBlurredCircle1Opacity": 0.2,
      "heroBlurredCircle2Color": "#1caa3a",
      "heroBlurredCircle2Opacity": 0.2,
      "heroPatternColor": "#ffffff",
      "heroPatternOpacity": 0.3,
      "heroLightBeam1Color": "#387e62",
      "heroLightBeam1Opacity": 0.2,
      "heroLightBeam2Color": "#387e62",
      "heroLightBeam2Opacity": 0.2,
      "contactSectionBgColor": "#7dd0ad1f",
      "contactInfoTitleText": "Contact Information",
      "contactInfoTitleColor": "#0c2217",
      "contactIconBgColor": "#7dd0ad42",
      "contactIconColor": "#0c2217",
      "contactLabelColor": "#111827",
      "contactTextColor": "#4b5563",
      "contactLinkHoverColor": "#2563eb",
      "phoneIcon": "PhoneIcon",
      "phoneLabel": "Phone",
      "phoneNumber": "(770) 495-0050",
      "phoneNumberLink": "tel:+17704950050",
      "emailIcon": "EnvelopeIcon",
      "emailLabel": "Email",
      "emailAddress": "support@example.com",
      "emailAddressLink": "mailto:support@example.com",
      "locationIcon": "MapPinIcon",
      "locationLabel": "Location",
      "locationAddress": "2785 Buford Hwy Ste 101-C,\nDuluth, GA 30096",
      "hoursIcon": "ClockIcon",
      "hoursLabel": "Business Hours",
      "hoursText": "Monday - Friday: 8:30 AM - 6:00 PM\nSaturday - Sunday: Closed",
      "googleMapEmbedUrl": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3311.6728431479!2d-83.46847632413687!3d33.891119080637714!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88f6732844d0854f%3A0x58a2e0e5cc8ccae7!2sDavis%20Tree!5e0!3m2!1sen!2sus!4v1717270133598!5m2!1sen!2sus",
      "googleMapHeight": "300px",
      "googleMapBorderRadius": "lg",
      "googleMapShadow": "lg",
      "formTitleText": "Send Us a Message",
      "formTitleColor": "#111827",
      "formLabelColor": "#374151",
      "formInputBgColor": "#ffffff",
      "formInputBorderColor": "#d1d5db",
      "formInputTextColor": "#111827",
      "formInputFocusRingColor": "#3b82f6",
      "formInputBorderRadius": "lg",
      "formInputPadding": "px-4 py-3",
      "formFieldFullName": "Full Name",
      "formFieldEmail": "Email Address",
      "formFieldPhone": "Phone Number",
      "formFieldService": "Service Needed",
      "formFieldMessage": "Message",
      "serviceOptions": [
        "General Inquiry",
        "Tree Removal",
        "Tree Trimming",
        "Stump Grinding",
        "Emergency Services",
        "Lot Clearing",
        "Consultation"
      ],
      "formSubmitBtnText": "Send Message",
      "formSubmitBtnBgColor": "#0c2217",
      "formSubmitBtnTextColor": "#ffffff",
      "formSubmitBtnHoverBgColor": "#367658",
      "formSubmitBtnBorderRadius": "lg",
      "ctaBgGradientFrom": "#1e40af",
      "ctaBgGradientVia": "#3b82f6",
      "ctaBgGradientTo": "#2563eb",
      "ctaPatternColor": "#ffffff",
      "ctaPatternOpacity": 0.05,
      "ctaCardBgColor": "#ffffff0d",
      "ctaCardBlurAmount": "2px",
      "ctaScheduleButtonText": "Schedule Now",
      "ctaScheduleButtonBgColor": "#ffffff",
      "ctaScheduleButtonTextColor": "#2563eb",
      "ctaScheduleButtonHoverBgColor": "#f3f4f6",
      "ctaCallButtonText": "Call Us Now",
      "ctaCallButtonBgColor": "#387e62",
      "ctaCallButtonTextColor": "#ffffff",
      "ctaCallButtonHoverBgColor": "#387e62",
      "ctaTitle": "Ready to Get ss Car Back to Perfect?",
      "ctaTitleColor": "#ffffff",
      "ctaDescription": "Schedule your e today and experience the difference expert auto body repair makes.",
      "ctaDescriptionColor": "#e0f2fe"
    }
  },
  "theme": {
    "primary600": "#2563eb",
    "primary700": "#1d4ed8"
  },
  "navLinks": [
    {
      "path": "/",
      "label": "Home"
    },
    {
      "path": "/services",
      "label": "Services"
    },
    {
      "path": "/reviews",
      "label": "Reviews"
    },
    {
      "path": "/contact",
      "label": "Contact"
    }
  ],
  "policies": {
    "terms": "Our terms of service text here.",
    "privacy": "Our privacy policy text here."
  },
  "description": "Professional tree removal services in Athens, GA",
  "contactInfo": {
    "address": "Athens, GA",
    "phone": "(706)-296-3318",
    "email": "jimmy@davistree.com"
  },
  "hours": {
    "weekday": "Monday - Friday: 9AM - 5PM",
    "weekend": "Closed"
  },
  "footerLinks": [
    {
      "path": "/",
      "label": "Home"
    },
    {
      "path": "/services",
      "label": "Services"
    },
    {
      "path": "/reviews",
      "label": "Reviews"
    },
    {
      "path": "/contact",
      "label": "Contact"
    }
  ],
  "socialLinks": {
    "twitter": "https://twitter.com/company",
    "facebook": "https://facebook.com/company",
    "linkedin": "https://linkedin.com/company/company",
    "instagram": "https://instagram.com/company"
  },
  "showJoinTeamButton": true,
  "joinTeamText": "Join the Team",
  "joinTeamLink": "/careers",
  "copyright": "© 2025 Davis Tree Service. All rights reserved.",
  "footerStyle": {
    "backgroundColor": "#ffffff",
    "gradientFromColor": "#9effcd",
    "gradientToColor": "#ffffff",
    "titleColor": "#000000",
    "textColor": "#000000",
    "linkColor": "#000000",
    "linkHoverColor": "#53a584",
    "socialIconColor": "#7dd0ae",
    "dividerColor": "rgba(253, 201, 201, 0.2)",
    "quickLinksTitleColor": "#ffffff",
    "contactInfoTitleColor": "#ffffff",
    "infoTitleColor": "#ffffff",
    "joinButtonBgColor": "#387e62",
    "joinButtonTextColor": "#030303",
    "joinButtonHoverBgColor": "#7dd0ae",
    "hoursCardBgColor": "rgba(245, 245, 245, 0.04)",
    "hoursCardTextColor": "#f5f5f5",
    "hoursCardValueColor": "#ffffff",
    "copyrightTextColor": "#6b7280",
    "policyLinkColor": "#f0f0f0",
    "policyLinkHoverColor": "#eebfbf"
  },
  "schedulingButtonText": "Schedule Now",
  "themeColor": "#f5d6d6",
  "themeLink": "",
  "companyName": "Davis Tree Service"
};

export default localConfig;